/**
 * ❌ Please do not edit this file.
 */

export type Currency = "USD" | "EUR";

export type InstrumentSymbol =
  | "BTC"
  | "ETH"
  | "SP500"
  | "US100"
  | "EURUSD"
  | "TSLA"
  | "AAPL";

export type InstrumentCategory = "crypto" | "stocks" | "forex" | "indicies";

export type Instrument = {
  code: InstrumentSymbol;
  category: InstrumentCategory;
  pair: [Currency | InstrumentSymbol, Currency | InstrumentSymbol];
  name: string;
  lastQuote: number;
};
