/**
 * ❌ Please do not edit this file.
 */

import { Instrument, InstrumentSymbol } from "./instrument.types";

export type WebSocketMessage =
  | string
  | ArrayBuffer
  | SharedArrayBuffer
  | Blob
  | ArrayBufferView;

/**
 * Message type that's sent from the server to the client
 */
export type WebSocketServerMessageJson = {
  type: "update";
  instruments: Instrument[];
};

/**
 * Message type that's sent from the client to the server
 */
export type WebSocketClientMessageJson =
  | {
      type: "subscribe";
      instrumentSymbols: InstrumentSymbol[];
    }
  | {
      type: "unsubscribe";
      instrumentSymbols: InstrumentSymbol[];
    };

export type JsonPrimitive = string | number | boolean | null;
export type JsonObject = { [Key in string]?: JsonValue | JsonPrimitive };
export type JsonArray = JsonValue[] | JsonPrimitive[];
export type JsonValue = JsonObject | JsonArray;
